import { useBrandConfig } from "@/hooks/useBrandConfig";
import React from "react";
import { StyleSheet, Text, View } from "react-native";

// Import auto-generated logo registry
// This file is automatically generated by scripts/prebuild.js
// No manual updates needed when adding new brands!
import { BRAND_LOGOS } from "@/brands/logoRegistry";

interface BrandLogoProps {
  width?: number;
  height?: number;
  style?: any;
}

export function BrandLogo({ width = 120, height = 40, style }: BrandLogoProps) {
  const { brandConfig, loading } = useBrandConfig();

  if (loading || !brandConfig) {
    return <View style={[styles.container, { width, height }, style]} />;
  }

  // Dynamically select logo component from registry
  const LogoComponent = BRAND_LOGOS[brandConfig.shortcode];

  // Fallback if brand logo not found in registry
  if (!LogoComponent) {
    console.warn(`Logo not found for brand: ${brandConfig.shortcode}`);
    return (
      <View style={[styles.container, { width, height }, style]}>
        <Text style={styles.fallbackText}>{brandConfig.displayName}</Text>
      </View>
    );
  }

  return (
    <View style={[styles.container, { width, height }, style]}>
      <LogoComponent width={width} height={height} style={styles.logo} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  logo: {
    flex: 1,
  },
  fallbackText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
});
