// This file is auto-generated by the prebuild script
// DO NOT EDIT MANUALLY - Brand validation safeguards

export const BRAND_VALIDATION = {
  EXPECTED_BRAND: 'nt',
  EXPECTED_BUNDLE_ID: 'metropolis.net.nursingtimes',
  EXPECTED_DISPLAY_NAME: 'Nursing Times',
  GENERATED_AT: '2025-11-11T22:46:11.658Z',
  SAFEGUARD_VERSION: '1.0.0'
};

// Runtime brand validation function
export function validateBrandConfiguration(): {
  isValid: boolean;
  errors: string[];
  warnings: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];
  
  // Check environment brand matches expected
  const envBrand = process.env.EXPO_PUBLIC_BRAND;
  if (envBrand !== BRAND_VALIDATION.EXPECTED_BRAND) {
    errors.push(`Environment brand mismatch: expected '${BRAND_VALIDATION.EXPECTED_BRAND}', got '${envBrand}'`);
  }
  
  // Validate bundle identifier consistency
  const expectedBundlePattern = BRAND_VALIDATION.EXPECTED_BRAND === 'cn'
    ? /metropolis\.co\.uk\.constructionnews/
    : /metropolis\.net\.nursingtimes/;
    
  if (!expectedBundlePattern.test(BRAND_VALIDATION.EXPECTED_BUNDLE_ID)) {
    errors.push(`Bundle ID pattern mismatch for brand '${BRAND_VALIDATION.EXPECTED_BRAND}'`);
  }
  
  // Check for stale configuration (older than 24 hours)
  const generatedTime = new Date(BRAND_VALIDATION.GENERATED_AT);
  const now = new Date();
  const hoursDiff = (now.getTime() - generatedTime.getTime()) / (1000 * 60 * 60);
  
  if (hoursDiff > 24) {
    warnings.push(`Brand configuration is ${Math.round(hoursDiff)} hours old. Consider regenerating.`);
  }
  
  return {
    isValid: errors.length === 0,
    errors,
    warnings
  };
}

// Development mode brand indicator
export function getBrandIndicator(): string {
  const isDev = __DEV__ || process.env.NODE_ENV === 'development';
  if (!isDev) return '';
  
  const brandColors = {
    cn: '🟠', // Orange for Construction News
    nt: '🔵'  // Blue for Nursing Times
  };
  
  return `${brandColors[BRAND_VALIDATION.EXPECTED_BRAND] || '⚪'} ${BRAND_VALIDATION.EXPECTED_DISPLAY_NAME}`;
}
