/**
 * Font Loader Utility
 * 
 * Automatically generated by scripts/font-importer.js
 * Do not edit this file manually - run the font importer script instead.
 * 
 * For native builds (iOS/Android), fonts are automatically linked by this script.
 */

/**
 * All available fonts
 * Fonts are automatically imported from assets/fonts/
 */
const fontFiles = {
  'Klavika-Regular-Regular': require('../assets/fonts/Klavika-Regular-Regular.otf'),
  'OpenSans-Bold': require('../assets/fonts/Open Sans/OpenSans-Bold.ttf'),
  'OpenSans-BoldItalic': require('../assets/fonts/Open Sans/OpenSans-BoldItalic.ttf'),
  'OpenSans-ExtraBold': require('../assets/fonts/Open Sans/OpenSans-ExtraBold.ttf'),
  'OpenSans-ExtraBoldItalic': require('../assets/fonts/Open Sans/OpenSans-ExtraBoldItalic.ttf'),
  'OpenSans-Italic': require('../assets/fonts/Open Sans/OpenSans-Italic.ttf'),
  'OpenSans-Light': require('../assets/fonts/Open Sans/OpenSans-Light.ttf'),
  'OpenSans-LightItalic': require('../assets/fonts/Open Sans/OpenSans-LightItalic.ttf'),
  'OpenSans-Medium': require('../assets/fonts/Open Sans/OpenSans-Medium.ttf'),
  'OpenSans-MediumItalic': require('../assets/fonts/Open Sans/OpenSans-MediumItalic.ttf'),
  'OpenSans-Regular': require('../assets/fonts/Open Sans/OpenSans-Regular.ttf'),
  'OpenSans-SemiBold': require('../assets/fonts/Open Sans/OpenSans-SemiBold.ttf'),
  'OpenSans-SemiBoldItalic': require('../assets/fonts/Open Sans/OpenSans-SemiBoldItalic.ttf'),
  'OpenSans_Condensed-Bold': require('../assets/fonts/Open Sans/OpenSans_Condensed-Bold.ttf'),
  'OpenSans_Condensed-BoldItalic': require('../assets/fonts/Open Sans/OpenSans_Condensed-BoldItalic.ttf'),
  'OpenSans_Condensed-ExtraBold': require('../assets/fonts/Open Sans/OpenSans_Condensed-ExtraBold.ttf'),
  'OpenSans_Condensed-ExtraBoldItalic': require('../assets/fonts/Open Sans/OpenSans_Condensed-ExtraBoldItalic.ttf'),
  'OpenSans_Condensed-Italic': require('../assets/fonts/Open Sans/OpenSans_Condensed-Italic.ttf'),
  'OpenSans_Condensed-Light': require('../assets/fonts/Open Sans/OpenSans_Condensed-Light.ttf'),
  'OpenSans_Condensed-LightItalic': require('../assets/fonts/Open Sans/OpenSans_Condensed-LightItalic.ttf'),
  'OpenSans_Condensed-Medium': require('../assets/fonts/Open Sans/OpenSans_Condensed-Medium.ttf'),
  'OpenSans_Condensed-MediumItalic': require('../assets/fonts/Open Sans/OpenSans_Condensed-MediumItalic.ttf'),
  'OpenSans_Condensed-Regular': require('../assets/fonts/Open Sans/OpenSans_Condensed-Regular.ttf'),
  'OpenSans_Condensed-SemiBold': require('../assets/fonts/Open Sans/OpenSans_Condensed-SemiBold.ttf'),
  'OpenSans_Condensed-SemiBoldItalic': require('../assets/fonts/Open Sans/OpenSans_Condensed-SemiBoldItalic.ttf'),
  'OpenSans_SemiCondensed-Bold': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-Bold.ttf'),
  'OpenSans_SemiCondensed-BoldItalic': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-BoldItalic.ttf'),
  'OpenSans_SemiCondensed-ExtraBold': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-ExtraBold.ttf'),
  'OpenSans_SemiCondensed-ExtraBoldItalic': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-ExtraBoldItalic.ttf'),
  'OpenSans_SemiCondensed-Italic': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-Italic.ttf'),
  'OpenSans_SemiCondensed-Light': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-Light.ttf'),
  'OpenSans_SemiCondensed-LightItalic': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-LightItalic.ttf'),
  'OpenSans_SemiCondensed-Medium': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-Medium.ttf'),
  'OpenSans_SemiCondensed-MediumItalic': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-MediumItalic.ttf'),
  'OpenSans_SemiCondensed-Regular': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-Regular.ttf'),
  'OpenSans_SemiCondensed-SemiBold': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-SemiBold.ttf'),
  'OpenSans_SemiCondensed-SemiBoldItalic': require('../assets/fonts/Open Sans/OpenSans_SemiCondensed-SemiBoldItalic.ttf'),
  'SpaceMono-Regular': require('../assets/fonts/SpaceMono-Regular.ttf'),
  'antenna-cond': require('../assets/fonts/antenna-cond.ttf'),
};

/**
 * Get all available fonts
 * @returns Object with font names as keys and require paths as values
 */
export function getAllFonts(): Record<string, any> {
  return fontFiles;
}

/**
 * Get font names for logging/debugging
 * @returns Array of available font names
 */
export function getAvailableFontNames(): string[] {
  return Object.keys(fontFiles);
}
