/**
 * Font Loader Utility
 * 
 * Automatically generated by scripts/font-importer.js
 * Do not edit this file manually - run the font importer script instead.
 * 
 * For native builds (iOS/Android), fonts are automatically linked by this script.
 */

/**
 * All available fonts
 * Fonts are automatically imported from assets/fonts/
 */
const fontFiles = {
  'Klavika-Regular-Regular': require('../assets/fonts/Klavika-Regular-Regular.otf'),
  'SpaceMono-Regular': require('../assets/fonts/SpaceMono-Regular.ttf'),
};

/**
 * Get all available fonts
 * @returns Object with font names as keys and require paths as values
 */
export function getAllFonts(): Record<string, any> {
  return fontFiles;
}

/**
 * Get font names for logging/debugging
 * @returns Array of available font names
 */
export function getAvailableFontNames(): string[] {
  return Object.keys(fontFiles);
}
