// This file is auto-generated by the prebuild script
// DO NOT EDIT MANUALLY - it will be overwritten
// Generated at: 2025-11-06T09:45:31.956Z

// Auto-generated brand editor image imports
import NTEditorImage from "@/brands/nt/editor.jpg";

// Editor image registry - maps brand shortcodes to their editor images
export const BRAND_EDITOR_IMAGES: Record<string, any> = {
  nt: NTEditorImage,
};

// Available brand shortcodes with editor images
export const AVAILABLE_EDITOR_IMAGE_BRANDS = ['nt'] as const;

// Type for brand shortcodes with editor images
export type BrandEditorImageShortcode = typeof AVAILABLE_EDITOR_IMAGE_BRANDS[number];

// Check if a brand has an editor image in the registry
export function hasBrandEditorImage(shortcode: string): shortcode is BrandEditorImageShortcode {
  return shortcode in BRAND_EDITOR_IMAGES;
}

// Get editor image for a brand (returns null if not available)
export function getBrandEditorImage(shortcode: string): any | null {
  return BRAND_EDITOR_IMAGES[shortcode] || null;
}
