// This file is auto-generated by the prebuild script
// DO NOT EDIT MANUALLY - it will be overwritten
// Generated at: 2025-10-20T16:52:16.412Z

import React from "react";

// Auto-generated brand logo imports
import CNLogo from "@/brands/cn/logo.svg";
import JNLLogo from "@/brands/jnl/logo.svg";
import NTLogo from "@/brands/nt/logo.svg";

// Logo registry - maps brand shortcodes to their logo components
export const BRAND_LOGOS: Record<string, React.ComponentType<any>> = {
  cn: CNLogo,
  jnl: JNLLogo,
  nt: NTLogo,
};

// Available brand shortcodes with logos
export const AVAILABLE_LOGO_BRANDS = ['cn', 'jnl', 'nt'] as const;

// Type for brand shortcodes with logos
export type BrandLogoShortcode = typeof AVAILABLE_LOGO_BRANDS[number];

// Check if a brand has a logo in the registry
export function hasBrandLogo(shortcode: string): shortcode is BrandLogoShortcode {
  return shortcode in BRAND_LOGOS;
}
