// This file is auto-generated by the prebuild script
// DO NOT EDIT MANUALLY - it will be overwritten
// Generated at: 2025-11-06T09:45:31.955Z

import React from "react";

// Auto-generated brand logo imports
import CNLogo from "@/brands/cn/logo.svg";
import JNLLogo from "@/brands/jnl/logo.svg";
import NTLogo from "@/brands/nt/logo.svg";
import NTHeaderLogo from "@/brands/nt/logo-header.svg";
import NTHeaderDarkLogo from "@/brands/nt/logo-header-dark.svg";

// Logo registry - maps brand shortcodes to their logo components
export const BRAND_LOGOS: Record<string, React.ComponentType<any>> = {
  cn: CNLogo,
  jnl: JNLLogo,
  nt: NTLogo,
};

// Header logo registry - maps brand shortcodes to their header logo components
export const BRAND_HEADER_LOGOS: Record<string, React.ComponentType<any>> = {
  nt: NTHeaderLogo,
};

// Header dark logo registry - maps brand shortcodes to their dark mode header logo components
export const BRAND_HEADER_DARK_LOGOS: Record<string, React.ComponentType<any>> = {
  nt: NTHeaderDarkLogo,
};

// Available brand shortcodes with logos
export const AVAILABLE_LOGO_BRANDS = ['cn', 'jnl', 'nt'] as const;

// Type for brand shortcodes with logos
export type BrandLogoShortcode = typeof AVAILABLE_LOGO_BRANDS[number];

// Check if a brand has a logo in the registry
export function hasBrandLogo(shortcode: string): shortcode is BrandLogoShortcode {
  return shortcode in BRAND_LOGOS;
}

// Check if a brand has a header logo in the registry
export function hasBrandHeaderLogo(shortcode: string): boolean {
  return shortcode in BRAND_HEADER_LOGOS;
}

// Check if a brand has a dark header logo in the registry
export function hasBrandHeaderDarkLogo(shortcode: string): boolean {
  return shortcode in BRAND_HEADER_DARK_LOGOS;
}
